python train.py \
--trial 4006 \
--dataset football \
--model brits \
--target_type imputation \
--missing_pattern playerwise \
--n_players 6 \
--n_features 2 \
--train_nfl \
--valid_nfl \
--rnn_dim 512 \
--dropout 0.0 \
--cartesian_accel \
--n_epochs 100 \
--start_lr 1e-3 \
--min_lr 1e-5 \
--batch_size 16 \
--print_every_batch 50 \
--save_every_epoch 50 \
--seed 100 \
--cuda \
--flip_pitch \