python train.py \
--trial 81 \
--dataset football \
--model graph_imputer \
--target_type imputation \
--n_players 3 \
--n_features 6 \
--train_nfl \
--valid_nfl \
--pe_z_dim 64 \
--pi_z_dim 32 \
--rnn_dim 64 \
--hybrid_rnn_dim 512 \
--n_layers 3 \
--n_heads 4 \
--dropout 0.0 \
--physics_loss \
--cartesian_accel \
--transformer \
--fpe \
--fpi \
--dynamic_hybrid \
--bidirectional \
--dynamic_missing \
--stochastic \
--seperate_learning \
--n_epochs 100 \
--start_lr 1e-3 \
--min_lr 1e-5 \
--batch_size 64 \
--print_every_batch 50 \
--save_every_epoch 50 \
--seed 100 \
--var_dim 16 \
--kld_weight_float 0.01 \
--cuda \
--flip_pitch \
--missing_prob_float 0.6 \
--m_pattern playerwise