#!/bin/bash
python train.py \
--trial 5001 \
--dataset basketball \
--model naomi \
--target_type imputation \
--missing_pattern all_player \
--n_players 5 \
--n_features 2 \
--train_nba \
--valid_nba \
--rnn_dim 300 \
--dec1_dim 200 \
--dec2_dim 200 \
--dec4_dim 200 \
--dec8_dim 200 \
--dec16_dim 200 \
--n_layers 2 \
--n_highest 4 \
--cartesian_accel \
--xy_sort \
--stochastic \
--n_epochs 100 \
--start_lr 1e-3 \
--min_lr 1e-5 \
--batch_size 64 \
--print_every_batch 50 \
--save_every_epoch 50 \
--seed 100 \
--clip 10 \
--max_iter_num 80000 \
--cuda \
--normalize \
--flip_pitch \